version: '2.1'
services:
  app:
    build:
      context: ./docker/app
    image: cms/app:latest
    ports:
      - "${DOCKER_APP_PORT}:80"
      - 8088:443
    volumes:
      - ./docker/app/worker.conf:/etc/supervisor/conf.d/worker.conf
      - .:/var/www/html:cached
    networks:
      - cms
  redis:
    build:
      context: ./docker/redis
    image: cms/redis:latest
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    volumes:
      - ./docker/redis/data:/data
    networks:
      - cms
  mysql:
    build:
      context: ./docker/mysql
    image: cms/mysql:latest
    command:
      --max_allowed_packet=64MB
      --key_buffer_size=500M
      --table_open_cache=4000
      --sort_buffer_size=3M
      --read_buffer_size=2M
      --read_rnd_buffer_size=8M
      --myisam_sort_buffer_size=64M
      --max_connections=400
      --query_cache_type=1
      --query_cache_limit=5M
      --query_cache_size=500M
      --tmp_table_size=20M
      --max_heap_table_size=20M
      --thread_cache_size=64
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - cms
volumes:
  redisdata:
    driver: local
  mysqldata:
    driver: local

networks:
  cms:
    driver: bridge
